# Generated by Django 3.1 on 2020-08-30 10:21

import beers.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcohol by volume')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='Is filtered?')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Pale Lager'), (2, 'Blonde Ale'), (3, 'Hefeweizen'), (4, 'Pale Ale'), (5, 'IPA'), (6, 'Amber Ale'), (7, 'Irish Red Ale'), (8, 'Brown Ale'), (9, 'Porter'), (10, 'Stout')], default=0, verbose_name='Color')),
                ('image', models.ImageField(blank=True, null=True, upload_to=beers.utils.image_upload_location, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('beers', models.ManyToManyField(blank=True, related_name='special_ingredients', to='beers.Beer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialingredient_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialingredient_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Special ingredient',
                'verbose_name_plural': 'Special ingredients',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_last_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='beers.company'),
        ),
        migrations.AddField(
            model_name='beer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beer_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beer_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
